# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_frame.setStyleSheet("background-color: rgb(20, 33, 61);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.top_frame)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(240, 16777215))
        self.label.setStyleSheet("font: 25 12pt \"Segoe UI Light\" bold;\n"
"background-color: rgb(20, 33, 61);\n"
"color: rgb(255, 255, 255);")
        self.label.setLineWidth(1)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.top_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(360, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(20, 33, 61);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_run = QtWidgets.QPushButton(self.frame_3)
        self.btn_run.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_run.setStyleSheet("font: 25 11.5pt \"Segoe UI Light\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 170, 127);")
        self.btn_run.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/img/btn_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_run.setIcon(icon)
        self.btn_run.setIconSize(QtCore.QSize(64, 32))
        self.btn_run.setCheckable(False)
        self.btn_run.setChecked(False)
        self.btn_run.setFlat(True)
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_5.addWidget(self.btn_run)
        self.btn_settings = QtWidgets.QPushButton(self.frame_3)
        self.btn_settings.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setStyleSheet("font: 25 11.5pt \"Segoe UI Light\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_settings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/img/iconfinder_Configuration-01_1976051.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon1)
        self.btn_settings.setIconSize(QtCore.QSize(32, 32))
        self.btn_settings.setFlat(True)
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_5.addWidget(self.btn_settings)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.pwr_btn = QtWidgets.QPushButton(self.top_frame)
        self.pwr_btn.setMaximumSize(QtCore.QSize(48, 32))
        self.pwr_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pwr_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/img/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pwr_btn.setIcon(icon2)
        self.pwr_btn.setIconSize(QtCore.QSize(48, 32))
        self.pwr_btn.setFlat(True)
        self.pwr_btn.setObjectName("pwr_btn")
        self.horizontalLayout_2.addWidget(self.pwr_btn)
        self.verticalLayout.addWidget(self.top_frame)
        self.middle_frame = QtWidgets.QFrame(self.centralwidget)
        self.middle_frame.setStyleSheet("background-color: rgb(20, 33, 61);")
        self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.middle_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_display_frame = QtWidgets.QFrame(self.middle_frame)
        self.graph_display_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graph_display_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph_display_frame.setObjectName("graph_display_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.graph_display_frame)
        self.verticalLayout_13.setContentsMargins(5, 5, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gv_pressure = PlotWidget(self.graph_display_frame)
        self.gv_pressure.setAutoFillBackground(False)
        self.gv_pressure.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gv_pressure.setFrameShape(QtWidgets.QFrame.Box)
        self.gv_pressure.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gv_pressure.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        brush = QtGui.QBrush(QtGui.QColor(252, 163, 17))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.gv_pressure.setForegroundBrush(brush)
        self.gv_pressure.setObjectName("gv_pressure")
        self.verticalLayout_13.addWidget(self.gv_pressure)
        self.gv_flow = PlotWidget(self.graph_display_frame)
        self.gv_flow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gv_flow.setFrameShape(QtWidgets.QFrame.Box)
        self.gv_flow.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        brush = QtGui.QBrush(QtGui.QColor(252, 163, 17))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.gv_flow.setForegroundBrush(brush)
        self.gv_flow.setObjectName("gv_flow")
        self.verticalLayout_13.addWidget(self.gv_flow)
        self.gv_volume = PlotWidget(self.graph_display_frame)
        self.gv_volume.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gv_volume.setFrameShape(QtWidgets.QFrame.Box)
        self.gv_volume.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        brush = QtGui.QBrush(QtGui.QColor(252, 163, 17))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.gv_volume.setForegroundBrush(brush)
        self.gv_volume.setObjectName("gv_volume")
        self.verticalLayout_13.addWidget(self.gv_volume)
        self.horizontalLayout.addWidget(self.graph_display_frame)
        self.right_frame = QtWidgets.QFrame(self.middle_frame)
        self.right_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.right_frame)
        self.frame_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_12.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        self.label_13.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.lbl_pressure_peak = QtWidgets.QLabel(self.frame_12)
        self.lbl_pressure_peak.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_pressure_peak.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_pressure_peak.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pressure_peak.setObjectName("lbl_pressure_peak")
        self.verticalLayout_8.addWidget(self.lbl_pressure_peak)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.right_frame)
        self.frame_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_13.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.lbl_peep = QtWidgets.QLabel(self.frame_13)
        self.lbl_peep.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_peep.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_peep.setObjectName("lbl_peep")
        self.verticalLayout_10.addWidget(self.lbl_peep)
        self.verticalLayout_2.addWidget(self.frame_13)
        self.frame_10 = QtWidgets.QFrame(self.right_frame)
        self.frame_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_10.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_11.addWidget(self.label_19)
        self.lbl_flow = QtWidgets.QLabel(self.frame_10)
        self.lbl_flow.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_flow.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_flow.setObjectName("lbl_flow")
        self.verticalLayout_11.addWidget(self.lbl_flow)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.right_frame)
        self.frame_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_11.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.frame_11)
        self.label_21.setStyleSheet("font: 25 12pt \"Segoe UI Light\" bold;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.lbl_tidal_volume = QtWidgets.QLabel(self.frame_11)
        self.lbl_tidal_volume.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_tidal_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tidal_volume.setObjectName("lbl_tidal_volume")
        self.verticalLayout_12.addWidget(self.lbl_tidal_volume)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.right_frame)
        self.frame_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_9.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.lbl_mode = QtWidgets.QLabel(self.frame_9)
        self.lbl_mode.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mode.setObjectName("lbl_mode")
        self.verticalLayout_9.addWidget(self.lbl_mode)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout.addWidget(self.right_frame)
        self.verticalLayout.addWidget(self.middle_frame)
        self.bottom_frame = QtWidgets.QFrame(self.centralwidget)
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.bottom_frame.setStyleSheet("background-color: rgb(20, 33, 61);")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.alarm_color = QtWidgets.QFrame(self.bottom_frame)
        self.alarm_color.setMaximumSize(QtCore.QSize(150, 16777215))
        self.alarm_color.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.alarm_color.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.alarm_color.setFrameShadow(QtWidgets.QFrame.Plain)
        self.alarm_color.setObjectName("alarm_color")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.alarm_color)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.alarm_color)
        self.label_3.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.alarm_status = QtWidgets.QLabel(self.alarm_color)
        self.alarm_status.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.alarm_status.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_status.setObjectName("alarm_status")
        self.verticalLayout_3.addWidget(self.alarm_status)
        self.horizontalLayout_6.addWidget(self.alarm_color)
        self.frame_5 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_5.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lbl_power_source = QtWidgets.QLabel(self.frame_5)
        self.lbl_power_source.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;\n"
"color: rgb(0, 255, 0);")
        self.lbl_power_source.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_power_source.setObjectName("lbl_power_source")
        self.verticalLayout_4.addWidget(self.lbl_power_source)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.lbl_fio2 = QtWidgets.QLabel(self.frame_6)
        self.lbl_fio2.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_fio2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fio2.setObjectName("lbl_fio2")
        self.verticalLayout_5.addWidget(self.lbl_fio2)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_7.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.lbl_resp_rate = QtWidgets.QLabel(self.frame_7)
        self.lbl_resp_rate.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_resp_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resp_rate.setObjectName("lbl_resp_rate")
        self.verticalLayout_6.addWidget(self.lbl_resp_rate)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_8.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(252, 163, 17);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setStyleSheet("font: 25 10pt \"Segoe UI Light\" bold;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.lbl_ieratio = QtWidgets.QLabel(self.frame_8)
        self.lbl_ieratio.setStyleSheet("font: 25 14pt \"Segoe UI Light\" bold;\n"
"border-radius: 5px;\n"
"background-color: #E5E5E5;")
        self.lbl_ieratio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ieratio.setObjectName("lbl_ieratio")
        self.verticalLayout_7.addWidget(self.lbl_ieratio)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.bottom_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPIRITUS VITAE"))
        self.label.setText(_translate("MainWindow", "Spiritus Vitae Ventilator"))
        self.label_13.setText(_translate("MainWindow", "Peak Pressure(cmH2O)"))
        self.lbl_pressure_peak.setText(_translate("MainWindow", "35"))
        self.label_17.setText(_translate("MainWindow", "PEEP(cmH2O)"))
        self.lbl_peep.setText(_translate("MainWindow", "5"))
        self.label_19.setText(_translate("MainWindow", "Flow(Lpm)"))
        self.lbl_flow.setText(_translate("MainWindow", "35"))
        self.label_21.setText(_translate("MainWindow", "V(mL)"))
        self.lbl_tidal_volume.setText(_translate("MainWindow", "500"))
        self.label_15.setText(_translate("MainWindow", "Mode"))
        self.lbl_mode.setText(_translate("MainWindow", "Assist"))
        self.label_3.setText(_translate("MainWindow", "Alarm"))
        self.alarm_status.setText(_translate("MainWindow", "--"))
        self.label_5.setText(_translate("MainWindow", "Power Source"))
        self.lbl_power_source.setText(_translate("MainWindow", "AC"))
        self.label_7.setText(_translate("MainWindow", "FiO2"))
        self.lbl_fio2.setText(_translate("MainWindow", "21%"))
        self.label_9.setText(_translate("MainWindow", "f(BPM)"))
        self.lbl_resp_rate.setText(_translate("MainWindow", "12"))
        self.label_11.setText(_translate("MainWindow", "I:E"))
        self.lbl_ieratio.setText(_translate("MainWindow", "1:2"))

from pyqtgraph import PlotWidget
import images_rc
